services:
  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html # Mount the entire Laravel project
      - ./public:/var/www/html/public # Explicitly mount the public directory
      - ./apache-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    networks:
      - webapp-network

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - webapp-network
    environment:
      - PHP_FPM_LISTEN=0.0.0.0:9000
      - PHP_ERROR_REPORTING=E_ALL
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=serverpulse"
      - "DB_USERNAME=user"
      - "DB_PASSWORD=password"

  node:
    image: node:18
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: >
      bash -c "npm install
      && npm run dev"
    networks:
      - webapp-network
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

  mysql:
    image: mysql:8.0
    command: --default-time-zone=+08:00
    environment:
      MYSQL_ROOT_PASSWORD: ariq12345    # Password for root user
      MYSQL_DATABASE: serverpulse    # Database will be created on startup
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Kuala_Lumpur
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webapp-network

  phpmyadmin:
    image: phpmyadmin:apache
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ariq12345    # Should match MYSQL_ROOT_PASSWORD above
      UPLOAD_LIMIT: 64M
    depends_on:
      - mysql
    networks:
      - webapp-network

volumes:
  mysql_data:

networks:
  webapp-network:
    driver: bridge